POST http://localhost:3000/reports
content-Type: application/json

{
  "make": "toyota",
  "model": "corolla",
  "year": 1980,
  "milage": 10000,
  "lng": 0,
  "lat": 0,
  "price": 50000
}

PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
  "approved": true
}

### Get an estimate for an esisting vehicle
GET http://localhost:3000/reports?make=toyota